services:
  - name: Tracker-Pro-Db
    type: web
    envVars:
      - key: POSTGRES_PASSWORD
        from: env
      - key: POSTGRES_DB
        from: env
      - key: POSTGRES_USER
        from: env
    buildCommand: docker pull postgres:latest
    startCommand: docker run --name Tracker-Pro-Db -p 7007:5432 -v ./tpdatabase/postgresql/data:/var/lib/postgresql/data/ -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -e POSTGRES_DB=$POSTGRES_DB -e POSTGRES_USER=$POSTGRES_USER postgres:latest

  - name: Tracker-Pro-Notifications
    type: web
    envVars:
      - key: GOTIFY_DEFAULTUSER_PASS
        from: env
      - key: GOTIFY_DEFAULTUSER_NAME
        from: env
    buildCommand: docker pull gotify/server:latest
    startCommand: docker run --name Tracker-Pro-Notifications -p $GOTIFY_PORT:80 -v ./tpnotifications/data:/app/data -e GOTIFY_DEFAULTUSER_PASS=$GOTIFY_DEFAULTUSER_PASS -e GOTIFY_DEFAULTUSER_NAME=$GOTIFY_DEFAULTUSER_NAME gotify/server:latest

  - name: Tracker-Pro-Qr-Code-Service
    type: web
    buildCommand: docker pull samwierema/go-qr-generator:latest
    startCommand: docker run --name Tracker-Pro-Qr-Code -p 8080:8080 samwierema/go-qr-generator:latest

  - name: Tracker-Pro-Gateway
    type: web
    envVars:
      - key: DB_MYSQL_HOST
        value: db
      - key: DB_MYSQL_PORT
        value: "3306"
      - key: DB_MYSQL_USER
        value: npm
      - key: DB_MYSQL_PASSWORD
        value: npm
      - key: DB_MYSQL_NAME
        value: npm
    buildCommand: docker pull jc21/nginx-proxy-manager:latest
    startCommand: docker run --name Tracker-Pro-Gateway -p 80:80 -p 443:443 -p 81:81 -v ./tpgateway/data:/data -v ./tpgateway/letsencrypt:/etc/letsencrypt -e DB_MYSQL_HOST=db -e DB_MYSQL_PORT=3306 -e DB_MYSQL_USER=npm -e DB_MYSQL_PASSWORD=npm -e DB_MYSQL_NAME=npm jc21/nginx-proxy-manager:latest
    dependsOn:
      - name: db

  - name: db
    type: web
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: npm
      - key: MYSQL_DATABASE
        value: npm
      - key: MYSQL_USER
        value: npm
      - key: MYSQL_PASSWORD
        value: npm
    buildCommand: docker pull jc21/mariadb-aria:latest
    startCommand: docker run --name db -v ./tpgateway/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=npm -e MYSQL_DATABASE=npm -e MYSQL_USER=npm -e MYSQL_PASSWORD=npm jc21/mariadb-aria:latest

  - name: farmer-logic
    type: web
    buildCommand: docker build -t farmer-logic -f ./apps/farmer-logic/Dockerfile .
    startCommand: docker run --name Tracker-Pro-Farmer-Logic -p 3002:3002 --env-file ./apps/farmer-logic/.env farmer-logic
    dependsOn:
      - name: Tracker-Pro-Db
      - name: Tracker-Pro-Gateway
      - name: Tracker-Pro-Notifications
      - name: Tracker-Pro-Qr-Code-Service

  - name: doctor-logic
    type: web
    buildCommand: docker build -t doctor-logic -f ./apps/doctor-logic/Dockerfile .
    startCommand: docker run --name Tracker-Pro-Doctor-Logic -p 3001:3001 --env-file ./apps/doctor-logic/.env doctor-logic
    dependsOn:
      - name: Tracker-Pro-Db
      - name: Tracker-Pro-Gateway
      - name: Tracker-Pro-Notifications
      - name: Tracker-Pro-Qr-Code-Service
